# Site settings
title: Pat Maddox & Associates, LLC
email: pat@patmaddox.com
description: > # this means to ignore newlines until "baseurl:"
  21st century collaborative software development & education
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.patmaddox.com" # the base hostname & protocol for your site
twitter_username: patmaddox
github_username:  patmaddox

# Build settings
markdown: kramdown
